/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Ssz.AI.Core.Grafana
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ListMetricPayloadOptionsRequest : IEquatable<ListMetricPayloadOptionsRequest>
    {
        /// <summary>
        /// Current metric.
        /// </summary>
        /// <value>Current metric.</value>
        [Required]
        [DataMember(Name="metric", EmitDefaultValue=false)]
        public string Metric { get; set; } = @"";

        /// <summary>
        /// Current payload.
        /// </summary>
        /// <value>Current payload.</value>
        [Required]
        [DataMember(Name="payload", EmitDefaultValue=false)]
        public Object Payload { get; set; } = @"";

        /// <summary>
        /// The payload name of the option list needs to be obtained.
        /// </summary>
        /// <value>The payload name of the option list needs to be obtained.</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListMetricPayloadOptionsRequest {\n");
            sb.Append("  Metric: ").Append(Metric).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ListMetricPayloadOptionsRequest)obj);
        }

        /// <summary>
        /// Returns true if ListMetricPayloadOptionsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ListMetricPayloadOptionsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListMetricPayloadOptionsRequest? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Metric == other.Metric ||
                    Metric != null &&
                    Metric.Equals(other.Metric)
                ) && 
                (
                    Payload == other.Payload ||
                    Payload != null &&
                    Payload.Equals(other.Payload)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the projection code
        /// </summary>
        /// <returns>Projection code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var projectionCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Metric != null)
                    projectionCode = projectionCode * 59 + Metric.GetHashCode();
                    if (Payload != null)
                    projectionCode = projectionCode * 59 + Payload.GetHashCode();
                    if (Name != null)
                    projectionCode = projectionCode * 59 + Name.GetHashCode();
                return projectionCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ListMetricPayloadOptionsRequest? left, ListMetricPayloadOptionsRequest? right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ListMetricPayloadOptionsRequest? left, ListMetricPayloadOptionsRequest? right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
