/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Ssz.AI.Core.Grafana
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class QueryRequestTarget : IEquatable<QueryRequestTarget>
    {
        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        /// <example>upper_25</example>
        [Required]
        [DataMember(Name="target", EmitDefaultValue=false)]
        public string Target { get; set; } = @"";

        /// <summary>
        /// Gets or Sets RefId
        /// </summary>
        [DataMember(Name="refId", EmitDefaultValue=false)]
        public string RefId { get; set; } = @"";

        /// <summary>
        /// arbitrary \&quot;additional data\&quot; the user can pass in
        /// </summary>
        /// <value>arbitrary \&quot;additional data\&quot; the user can pass in</value>
        [DataMember(Name="payload", EmitDefaultValue=false)]
        public Object? Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryRequestTargets {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  RefId: ").Append(RefId).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }        

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((QueryRequestTarget)obj);
        }

        /// <summary>
        /// Returns true if QueryRequestTargets instances are equal
        /// </summary>
        /// <param name="other">Instance of QueryRequestTargets to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryRequestTarget? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Target == other.Target ||
                    Target != null &&
                    Target.Equals(other.Target)
                ) && 
                (
                    RefId == other.RefId ||
                    RefId != null &&
                    RefId.Equals(other.RefId)
                ) && 
                (
                    Payload == other.Payload ||
                    Payload != null &&
                    Payload.Equals(other.Payload)
                );
        }

        /// <summary>
        /// Gets the projection code
        /// </summary>
        /// <returns>Projection code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var projectionCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Target != null)
                    projectionCode = projectionCode * 59 + Target.GetHashCode();
                    if (RefId != null)
                    projectionCode = projectionCode * 59 + RefId.GetHashCode();
                    if (Payload != null)
                    projectionCode = projectionCode * 59 + Payload.GetHashCode();
                return projectionCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(QueryRequestTarget? left, QueryRequestTarget? right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(QueryRequestTarget? left, QueryRequestTarget? right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
