/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Ssz.AI.Core.Grafana
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RawTimeFrame : IEquatable<RawTimeFrame>
    {
        /// <summary>
        /// Gets or Sets From
        /// </summary>
        /// <example>now-1h</example>
        [DataMember(Name="from", EmitDefaultValue=false)]
        public string From { get; set; } = @"";

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        /// <example>now</example>
        [DataMember(Name="to", EmitDefaultValue=false)]
        public string To { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RawTimeFrame {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RawTimeFrame)obj);
        }

        /// <summary>
        /// Returns true if RawTimeFrame instances are equal
        /// </summary>
        /// <param name="other">Instance of RawTimeFrame to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RawTimeFrame? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    From == other.From ||
                    From != null &&
                    From.Equals(other.From)
                ) && 
                (
                    To == other.To ||
                    To != null &&
                    To.Equals(other.To)
                );
        }

        /// <summary>
        /// Gets the projection code
        /// </summary>
        /// <returns>Projection code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var projectionCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (From != null)
                    projectionCode = projectionCode * 59 + From.GetHashCode();
                    if (To != null)
                    projectionCode = projectionCode * 59 + To.GetHashCode();
                return projectionCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RawTimeFrame? left, RawTimeFrame? right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RawTimeFrame? left, RawTimeFrame? right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
